<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPdJPjG4\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPdJPjG4/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPdJPjG4.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPdJPjG4\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPdJPjG4\App_KernelProdContainer([
    'container.build_hash' => 'PdJPjG4',
    'container.build_id' => 'c1dbb9e6',
    'container.build_time' => 1618406258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPdJPjG4');
