<?php

namespace ContainerO5zxzih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_W5gaOEWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.w5gaOEW' shared service.
     *
     * @return \App\Controller\MatiereRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ListController::editchute()": the $chuteRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MatiereRepository". Did you forget to add a use statement?');
    }
}
