<?php

namespace ContainerO5zxzih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z5ZfkypService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z5Zfkyp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z5Zfkyp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ListController::deleteMatiere' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController::editchute' => ['privates', '.service_locator.oDzfYMo', 'get_ServiceLocator_ODzfYMoService', true],
            'App\\Controller\\ListController::noUseChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController::showListChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController::useChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\MatiereController::deleteMatiere' => ['privates', '.service_locator.Vch4viH', 'get_ServiceLocator_Vch4viHService', true],
            'App\\Controller\\MatiereController::editMatiere' => ['privates', '.service_locator.iWaWs4c', 'get_ServiceLocator_IWaWs4cService', true],
            'App\\Controller\\MatiereController::manageMatiere' => ['privates', '.service_locator.iWaWs4c', 'get_ServiceLocator_IWaWs4cService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ListController:deleteMatiere' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController:editchute' => ['privates', '.service_locator.oDzfYMo', 'get_ServiceLocator_ODzfYMoService', true],
            'App\\Controller\\ListController:noUseChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController:showListChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\ListController:useChute' => ['privates', '.service_locator.2YOeMun', 'get_ServiceLocator_2YOeMunService', true],
            'App\\Controller\\MatiereController:deleteMatiere' => ['privates', '.service_locator.Vch4viH', 'get_ServiceLocator_Vch4viHService', true],
            'App\\Controller\\MatiereController:editMatiere' => ['privates', '.service_locator.iWaWs4c', 'get_ServiceLocator_IWaWs4cService', true],
            'App\\Controller\\MatiereController:manageMatiere' => ['privates', '.service_locator.iWaWs4c', 'get_ServiceLocator_IWaWs4cService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ListController::deleteMatiere' => '?',
            'App\\Controller\\ListController::editchute' => '?',
            'App\\Controller\\ListController::noUseChute' => '?',
            'App\\Controller\\ListController::showListChute' => '?',
            'App\\Controller\\ListController::useChute' => '?',
            'App\\Controller\\MatiereController::deleteMatiere' => '?',
            'App\\Controller\\MatiereController::editMatiere' => '?',
            'App\\Controller\\MatiereController::manageMatiere' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ListController:deleteMatiere' => '?',
            'App\\Controller\\ListController:editchute' => '?',
            'App\\Controller\\ListController:noUseChute' => '?',
            'App\\Controller\\ListController:showListChute' => '?',
            'App\\Controller\\ListController:useChute' => '?',
            'App\\Controller\\MatiereController:deleteMatiere' => '?',
            'App\\Controller\\MatiereController:editMatiere' => '?',
            'App\\Controller\\MatiereController:manageMatiere' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
