<?php

namespace ContainerO5zxzih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ODzfYMoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oDzfYMo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oDzfYMo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chuteRepository' => ['privates', '.errored.w5gaOEW', NULL, 'Cannot determine controller argument for "App\\Controller\\ListController::editchute()": the $chuteRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MatiereRepository". Did you forget to add a use statement?'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chuteRepository' => '?',
            'manager' => '?',
        ]);
    }
}
