<?php

namespace ContainerPdJPjG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChuteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ChuteRepository' shared autowired service.
     *
     * @return \App\Repository\ChuteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ChuteRepository'] = new \App\Repository\ChuteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
