<?php

namespace ContainerPdJPjG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatiereTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MatiereType' shared autowired service.
     *
     * @return \App\Form\MatiereType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MatiereType'] = new \App\Form\MatiereType();
    }
}
