<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerERZ3Fwu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerERZ3Fwu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerERZ3Fwu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerERZ3Fwu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerERZ3Fwu\App_KernelDevDebugContainer([
    'container.build_hash' => 'ERZ3Fwu',
    'container.build_id' => '6e867117',
    'container.build_time' => 1618350343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerERZ3Fwu');
